import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("기존 Publisher lease 경로를 유지한다",async()=>assert.match(await readFile(new URL("../src/index.js",import.meta.url),"utf8"),/\/api\/publisher\/lease/));
test("로그인 만료 결과를 서버가 login_required로 재처리 가능하게 유지한다",async()=>assert.match(await readFile(new URL("../../functions/api/publisher/result.js",import.meta.url),"utf8"),/login_required/));
test("재시도 가능한 실패만 queued로 복구한다",async()=>{const app=await readFile(new URL("../src/index.js",import.meta.url),"utf8");const api=await readFile(new URL("../../functions/api/publisher/result.js",import.meta.url),"utf8");assert.match(app,/retryable \? "retry" : "failed"/);assert.match(api,/outcome === "retry" \? "queued"/);assert.match(api,/claim_token=NULL/);});
test("임시저장 성공은 saved로 완료되어 다음 queued 조회에 다시 나오지 않는다",async()=>{const app=await readFile(new URL("../src/index.js",import.meta.url),"utf8");const queue=await readFile(new URL("../../functions/api/publisher/queued.js",import.meta.url),"utf8");assert.match(app,/result: "saved"/);assert.match(queue,/j\.status='queued'/);assert.doesNotMatch(queue,/saved[^\n]*queued/);});
test("동일 draft 활성 작업은 unique index로 하나만 허용하고 완료 URL과 시간을 저장한다",async()=>{const migration=await readFile(new URL("../../migrations/0009_rss_collection_publish_jobs.sql",import.meta.url),"utf8");const result=await readFile(new URL("../../functions/api/publisher/result.js",import.meta.url),"utf8");assert.match(migration,/UNIQUE INDEX[\s\S]*publish_jobs\(draft_id\)[\s\S]*status IN \('queued','processing'\)/);assert.match(result,/naver_draft_url/);assert.match(result,/completed_at/);});
test("승인 이미지 다운로드 URL은 R2 키를 노출하지 않는다",async()=>{const src=await readFile(new URL("../../functions/api/publisher/queued.js",import.meta.url),"utf8");assert.match(src,/processed_r2_key IS NOT NULL/);assert.match(src,/download_url/);assert.doesNotMatch(src,/SELECT[^`]*processed_r2_key[^`]*FROM/);});
test("대기열 API는 승인 이미지를 최대 4장만 반환한다",async()=>{const src=await readFile(new URL("../../functions/api/publisher/queued.js",import.meta.url),"utf8");assert.match(src,/approved_for_use=1/);assert.match(src,/rights_status='approved'/);assert.match(src,/LIMIT 4/);assert.doesNotMatch(src,/images[^\n]*length[^\n]*[!=]==?\s*4/);});
test("에디터 필드 탐지 전에 기존 작성글 팝업을 처리한다",async()=>{const src=await readFile(new URL("../src/index.js",import.meta.url),"utf8");const popup=src.indexOf("dismissExistingDraftPopup(page)");const fields=src.indexOf("findEditorAcrossFrames(page, main.frame");assert.ok(popup>=0&&popup<fields);});
test("기존 작성글 팝업 문구와 취소 버튼을 제한한다",async()=>{const src=await readFile(new URL("../src/naver-selectors.js",import.meta.url),"utf8");assert.match(src,/작성 중인 글이 있습니다\|이어서 작성하시겠습니까/);assert.match(src,/getByRole\("button", \{ name: cancelButtonName \}\)/);assert.match(src,/state: "hidden", timeout: 10000/);});
